language:
    - python

python:
    - "3.3"

compiler:
    - clang
    - gcc

install:
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # install cmake toolchains and script
    - POLLY_VERSION="0.6.2"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_VERSION="3.2.1-ruslo"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   build.py --install --toolchain default --config Release --fwd "CMAKE_USE_SYSTEM_CURL=YES"
    -   export PATH="`pwd`/_install/default/bin:${PATH}"
    - cd ..
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

env:
    - BUILD_TYPE="Debug" TOOLCHAIN="clang_libstdcxx"
    - BUILD_TYPE="Release" TOOLCHAIN="clang_libstdcxx"
    - BUILD_TYPE="Debug" TOOLCHAIN="gcc48"
    - BUILD_TYPE="Release" TOOLCHAIN="gcc48"

script:
    - build.py --toolchain ${TOOLCHAIN} --verbose --test --config ${BUILD_TYPE} --fwd SOBER_RUN_LONG_TESTS=ON HUNTER_RUN_INSTALL=ON
